Project: Header with style
Daron976/Hello-world pull request #2
Opened 2022-08-16 17:49 UTC by Daron976

## Hello world project 

In this project I:

- Added an h1 header
- Changed the default text colour of the header
- Fixed errors and correct omissions

2022-08-16 18:18 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Daron976 👋🏻
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍🏻 

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* GitHub flow is followed correctly ✔️
* PR is descriptive and professional ✔️ 

## Required Changes:
- [x] README file should follow Microverse's [template](https://github.com/microverseinc/readme-template). Your README file is lacking many sections, kindly add them (Getting Started, Contributing, Show your support, Acknowledgments...) to make the project more professional ✨ 

## Optional:
- [ ] In the future, please refrain from creating a new branch and a new pull request if the reviewer asks for changes. Instead, make the changes in the same old branch and submit the same pull request again 😄 
- [ ] It's better to follow commit messages standards by making them capitalized and in the imperative form (Example: 'Add h1 header' instead of 'added h1 header'). This way, your commit history will be more readable and professional-looking ✨ 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 19:22 UTC, Kamba56 approved these changes
Hi @Daron976 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 19:22 UTC, Kamba56 commented on README.md
>  👤 **Author1**
- [ ] [Optional] You can add your name here instead of 'Author'

2022-08-16 19:22 UTC, Kamba56 commented on README.md
> +- SSH key for github linked to git on local environment
- [ ] [Optional] I think prerequisites of a project are things that you need to install locally before the project will run effectively locally. In that case, the prerequisites of this project should be `node js` and `npm`.😊

2022-08-16 20:09 UTC, merged

2022-10-11 06:55 UTC, Daron976 commented
Thank you so much

I wanted to change the commit message but I couldn’t alter it
In future I’ll definitely use better commit messages

On Tue, 16 Aug 2022 at 21:22, Toma John Musa ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @Daron976 <https://github.com/Daron976> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/Daron976/Hello-world/pull/2#discussion_r947163018>:
>
> >
>
>  ### Usage
>
>
>
>  - Demostrate competence concerning the professional presentation of project
>
>
>
> -## Authors
>
> +### Deployment
>
> +- Right click on the index.html file
>
> +- Select "Open with" / "Open with another application"
>
> +- Choose any browser from the options that appear
>
> +
>
> +## Author/s
>
>
>
>  👤 **Author1**
>
>
>
>    - [Optional] You can add your name here instead of 'Author'
>
> ------------------------------
>
> In README.md
> <https://github.com/Daron976/Hello-world/pull/2#discussion_r947170910>:
>
> >  ### Prerequisites
>
>
>
>  - Html & CSS basics
>
>  - Git & github
>
> +- SSH key for github linked to git on local environment
>
>
>
>    - [Optional] I think prerequisites of a project are things that you
>    need to install locally before the project will run effectively locally. In
>    that case, the prerequisites of this project should be node js and npm.
>    😊
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Daron976/Hello-world/pull/2#pullrequestreview-1074652281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQQJYFU6BH2D5VX5IAX6MEDVZPS7BANCNFSM56WWKCTA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>